// AUTO-GENERATED by scripts/generate-types.ts — do not edit by hand.
// Source of truth: GET https://api.skillos.network/openapi.json
// Regenerate via: npm run generate-types

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns API version, deployed commit, process uptime, and chain identity. Always 200 unless the function fails to start.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
                /** @description Unexpected error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/siwb/nonce": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a SIWB nonce
         * @description Issues a single-use 5-minute nonce for use in a SIWE message. If the wallet already has an outstanding nonce, the previous one is invalidated and a fresh one is returned (REPLACE pattern; UX rationale: cancel-and-retry flows shouldn't fail).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SiwbNonceRequest"];
                };
            };
            responses: {
                /** @description Nonce issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SiwbNonceResponse"];
                    };
                };
                /** @description Invalid input */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/siwb/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify SIWE signature → bearer JWT
         * @description Verifies a SIWE message + signature against the address. Order of checks: (1) parse + validate SIWE fields, (2) consume nonce atomically (single-use, replay-rejected), (3) viem.verifyMessage (handles ERC-6492 wrapper transparently for Base Account smart wallets). On success, issues a 24h HS256 JWT. Bearer is meant for Authorization: Bearer <token> on write endpoints.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SiwbVerifyRequest"];
                };
            };
            responses: {
                /** @description Verified — bearer issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SiwbVerifyResponse"];
                    };
                };
                /** @description Verification failed (signature, nonce, or message) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Invalid input shape */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/siwa/nonce": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a SIWA nonce
         * @description Issues a single-use 5-minute nonce. The nonce is wallet-agnostic at issue time — the agent address only appears inside the signed SIWA message at verify time. Stored in Supabase `skillos_siwa_nonces`; consume is atomic via DELETE...RETURNING.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SiwaNonceRequest"];
                };
            };
            responses: {
                /** @description Nonce issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SiwaNonceResponse"];
                    };
                };
                /** @description Nonce store unavailable (transient) */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/siwa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify SIWA signature → opaque receipt
         * @description Verifies a SIWA message + signature: (1) structural validation, (2) chain + registry binding match, (3) ECDSA/ERC-1271 signature recovery, (4) atomic nonce consume, (5) onchain ownerOf(agentId) check against ERC-8004 registry. On success, issues an HMAC receipt + fetches agent Builder Code from api.base.dev (best-effort).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SiwaVerifyRequest"];
                };
            };
            responses: {
                /** @description Verified — receipt issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SiwaVerifyResponse"];
                    };
                };
                /** @description Verification failed (signature, nonce, registry, or message) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Invalid input shape */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tournaments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tournaments
         * @description Paginated list of tournaments, newest-first. Derived from TournamentCreated events; per-tournament settled/participantsCount fields read via multicall.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Opaque cursor from a previous response. Pass back verbatim. */
                    cursor?: string;
                    /** @description Items per page (1-50). Defaults to 20. */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tournament list page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TournamentListResponse"];
                    };
                };
                /** @description Invalid query parameters */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tournaments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get tournament by id
         * @description Fresh on-chain state for a single tournament.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description bytes32 hex (e.g., tournament ID, transaction hash) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tournament state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tournament"];
                    };
                };
                /** @description Tournament does not exist */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Invalid id */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tournaments/{id}/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Score history for a tournament
         * @description All ScoreSubmitted events for the tournament, sorted by score descending (block number ascending as tiebreaker). Each row represents one submission, not best-per-player.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Opaque cursor from a previous response. Pass back verbatim. */
                    cursor?: string;
                    /** @description Items per page (1-50). Defaults to 20. */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description bytes32 hex (e.g., tournament ID, transaction hash) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Leaderboard page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LeaderboardResponse"];
                    };
                };
                /** @description Invalid params */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scores/{wallet}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Score submissions by wallet
         * @description All ScoreSubmitted events where player == :wallet, across every tournament. Sorted newest-first.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Opaque cursor from a previous response. Pass back verbatim. */
                    cursor?: string;
                    /** @description Items per page (1-50). Defaults to 20. */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description EVM wallet address (checksum or lowercase) */
                    wallet: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Score history page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ScoreHistoryResponse"];
                    };
                };
                /** @description Invalid params */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a score (T0 tier — signature-only, no plausibility)
         * @description Bearer-authenticated. Server signs a submitSoloScore attestation with STUDIO_PRIVATE_KEY and broadcasts on-chain (fire-and-forget; tx hash returned before block inclusion). Sprint X2 ships T0-only; T1+ submissions return 501 until plausibility pipeline is integrated (Phase 2 mainnet blocker). Game-app frontends should continue using their own per-game /api/tournaments/[id]/solo backends, which run AI plausibility checks.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ScoreSubmitRequest"];
                };
            };
            responses: {
                /** @description Submission broadcast on-chain */
                200: {
                    headers: {
                        "X-SkillOS-Tier": "T0";
                        "X-SkillOS-Verification": "signature-only";
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ScoreSubmitResponse"];
                    };
                };
                /** @description Bearer or input invalid */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limit exceeded (60/min per wallet) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Tier not implemented */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sponsors/{wallet}/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ERC-5192 SBT receipts owned by wallet
         * @description All PoolSponsored events where sponsor == :wallet. Each event corresponds to one soulbound receipt minted to the wallet. Soulbound = receipts are non-transferable, so the event ledger is a complete inventory.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Opaque cursor from a previous response. Pass back verbatim. */
                    cursor?: string;
                    /** @description Items per page (1-50). Defaults to 20. */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description EVM wallet address (checksum or lowercase) */
                    wallet: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sponsor receipts page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SponsorReceiptsResponse"];
                    };
                };
                /** @description Invalid params */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a score on behalf of a verified agent
         * @description Agent-authenticated via SIWA receipt + ERC-8128 per-request signature. Server signs a submitSoloScore attestation with STUDIO_PRIVATE_KEY and broadcasts on-chain. T0 tier only in v0.1; T1+ returns 501 (same constraint as POST /v1/scores). The signing wallet is the AGENT address (proven via SIWA + onchain ownerOf), NOT a separate user wallet.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AgentScoreSubmitRequest"];
                };
            };
            responses: {
                /** @description Submission broadcast on-chain */
                200: {
                    headers: {
                        "X-SkillOS-Tier": "T0";
                        "X-SkillOS-Verification": "siwa-erc8128";
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentScoreSubmitResponse"];
                    };
                };
                /** @description Receipt missing/invalid, ERC-8128 sig invalid, or input invalid */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limit exceeded (60/min per agent address) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update off-chain agent profile
         * @description Update display name + arbitrary preferences for the authenticated agent. On-chain identity (name, description, endpoints, pubkey) stays in the ERC-8004 registry — use that for identity changes; this endpoint is for off-chain UX metadata.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AgentProfilePatchRequest"];
                };
            };
            responses: {
                /** @description Profile updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentProfile"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/agents/matches/start-solo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a solo agent match (X20 spectator MVP + X15 paid retries)
         * @description Agent-authenticated via SIWA receipt + ERC-8128 per-request signature (Hotfix C1). Reserves a duel_runs row, inserts a pending x15_payment_attempts row, and returns 202 + runId. The handler does NOT block on x402 settlement or chargeRetryFee — those run in a background worker (waitUntil) along with the actual game loop. Spectator UI subscribes to two Realtime channels on the returned runId: duel_moves for move-by-move state, x15_payment_attempts for settlement progress (pending → x402_settled → anchored/skipped). The signing wallet that pays for x402 + chargeRetryFee remains the server agent (AGENT_PRIVATE_KEY); SIWA only gates who may trigger a spend.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SoloMatchStartRequest"];
                };
            };
            responses: {
                /** @description Match reserved; runId returned; x402 + chargeRetryFee + run loop kicked off asynchronously. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SoloMatchStartResponse"];
                    };
                };
                /** @description SIWA receipt missing/invalid, or ERC-8128 per-request signature missing/invalid. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate-limit exceeded (60/min per authenticated agent) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Reservation failed (database unavailable, signer misconfig) */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/data/match-replay/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tournament match replay (paywalled, T2 tier)
         * @description Returns per-submission event entries for a tournament — score, seed, duration, on-chain anchor. Replay-verifiable. Costs $0.01 USDC on Base Sepolia via x402; unauthenticated requests receive HTTP 402 with the payment requirements in the `PAYMENT-REQUIRED` response header. Phase 1 returns a hash-derived stubbed sample (`sampleData: true`); shape is the long-term contract.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description bytes32 hex (e.g., tournament ID, transaction hash) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paid request — match replay payload */
                200: {
                    headers: {
                        "X-SkillOS-Tier": "T2";
                        "X-SkillOS-Verification": "x402";
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatchReplay"];
                    };
                };
                /** @description Payment required. Body is empty per x402 v2; payment requirements are encoded in the `PAYMENT-REQUIRED` response header (base64-encoded JSON matching X402PaymentRequirements). */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["X402PaymentRequirements"];
                    };
                };
                /** @description Invalid tournament id */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/data/cohort-snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregated cohort snapshot (paywalled, T3 tier)
         * @description Cross-tournament aggregated statistics — totals, per-game breakdown, agent vs human submission split. Costs $0.10 USDC on Base Sepolia via x402; unauthenticated requests receive HTTP 402 with the payment requirements in the `PAYMENT-REQUIRED` response header. Phase 1 returns a fixed plausible sample (`sampleData: true`); shape is the long-term contract.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paid request — cohort snapshot payload */
                200: {
                    headers: {
                        "X-SkillOS-Tier": "T3";
                        "X-SkillOS-Verification": "x402";
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CohortSnapshot"];
                    };
                };
                /** @description Payment required. Body is empty per x402 v2; payment requirements are encoded in the `PAYMENT-REQUIRED` response header (base64-encoded JSON matching X402PaymentRequirements). */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["X402PaymentRequirements"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            version: string;
            commit: string;
            uptimeSeconds: number;
            /** @enum {string} */
            network: "base-sepolia";
            /** @enum {number} */
            chainId: 84532;
        };
        Error: {
            error: {
                /**
                 * @description Stable machine-readable code (e.g., NOT_FOUND, INVALID_PARAMS, INTERNAL).
                 * @example NOT_FOUND
                 */
                code: string;
                /** @description Human-readable description. */
                message: string;
                /** @description Optional structured detail (e.g., Zod issues array). */
                details?: unknown;
            };
        };
        SiwbNonceResponse: {
            /** @description Cryptographic random, 32 lowercase hex chars. Matches Base SIWE nonce regex `\w{32}$`. */
            nonce: string;
            /**
             * Format: date-time
             * @description ISO-8601, UTC. Equals server-side `now()` at issuance.
             */
            issuedAt: string;
            /**
             * Format: date-time
             * @description ISO-8601, UTC. issuedAt + 5 minutes.
             */
            expiresAt: string;
        };
        SiwbNonceRequest: {
            /**
             * @description EVM wallet address (checksum or lowercase)
             * @example 0x1234567890abcdef1234567890abcdef12345678
             */
            walletAddress: string;
        };
        SiwbVerifyResponse: {
            /** @description Bearer JWT (HS256, 24h TTL). Pass as `Authorization: Bearer <token>` to write endpoints. */
            token: string;
            /**
             * Format: date-time
             * @description ISO-8601, UTC. Token expiration.
             */
            expiresAt: string;
            /** Format: uuid */
            sessionId: string;
        };
        SiwbVerifyRequest: {
            /** @description Full SIWE-formatted message (EIP-4361). Server parses + validates. */
            message: string;
            /** @description EIP-191 personal_sign signature. Base Account smart wallets wrap with ERC-6492; viem.verifyMessage handles transparently. */
            signature: string;
            /**
             * @description Must equal the address inside the SIWE message body.
             * @example 0x1234567890abcdef1234567890abcdef12345678
             */
            walletAddress: string;
        };
        SiwaNonceResponse: {
            /** @description Cryptographic random alphanumeric nonce (default 16 hex chars). Single-use; consumed atomically at verify. */
            nonce: string;
            /**
             * Format: date-time
             * @description ISO-8601, UTC. Equals server-side `now()` at issuance.
             */
            issuedAt: string;
            /**
             * Format: date-time
             * @description ISO-8601, UTC. issuedAt + 5 minutes.
             */
            expiresAt: string;
        };
        SiwaNonceRequest: Record<string, never>;
        SiwaVerifyResponse: {
            /** @description HMAC-signed receipt (base64url(json).base64url(hmac-sha256)). Pass as `X-SIWA-Receipt` header on subsequent agent requests alongside ERC-8128 per-request signature. */
            receipt: string;
            /**
             * Format: date-time
             * @description ISO-8601, UTC. Receipt expiration (24h TTL).
             */
            expiresAt: string;
            /**
             * @description EVM wallet address (checksum or lowercase)
             * @example 0x1234567890abcdef1234567890abcdef12345678
             */
            address: string;
            /** @description ERC-8004 AgentIdentity tokenId owned by the address. */
            agentId: number;
            /**
             * @description `eoa` = externally-owned account, `sca` = smart contract account (ERC-1271).
             * @enum {string}
             */
            signerType: "eoa" | "sca";
            /** @description Agent Builder Code (bc_xxxxxxxx) returned by api.base.dev/v1/agents/builder-codes. Fetched server-side on verify success (Sprint X3 Q3a-refined trigger). Cached for receipt lifetime in caller. */
            builderCode?: string;
        };
        SiwaVerifyRequest: {
            /** @description Full SIWA-formatted message (EIP-191). Contains agentId, agentRegistry (CAIP-10), chainId, nonce, issuedAt, etc. */
            message: string;
            /** @description EIP-191 personal_sign by the agent. Verified via client.verifyMessage — supports EOA, ERC-1271 smart wallets, and ERC-6492 wrappers. */
            signature: string;
        };
        TournamentListResponse: {
            items: components["schemas"]["Tournament"][];
            pagination: {
                /** @description Cursor for the next page. Absent when no more results. */
                next?: string;
            };
        };
        Tournament: {
            /**
             * @description bytes32 hex (e.g., tournament ID, transaction hash)
             * @example 0xabcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789
             */
            id: string;
            /**
             * @description EVM wallet address (checksum or lowercase)
             * @example 0x1234567890abcdef1234567890abcdef12345678
             */
            sponsor: string;
            /**
             * @description Game slug, decoded from on-chain bytes32. Falls back to hex if not UTF-8 decodable.
             * @example 2048
             */
            game: string;
            /** @description Cycle enum (0=daily, 1=weekly, 2=monthly, ...) */
            cycleType: number;
            /** @description Unix seconds, tournament window start. */
            startsAt: number;
            /** @description Unix seconds, tournament window end. */
            endsAt: number;
            /**
             * @description USDC, 6 decimals (1_000_000 = $1).
             * @example 1000000
             */
            prizePool: string;
            /**
             * @description uint256 as decimal string (JSON cannot represent BigInt)
             * @example 1000000
             */
            participationBonus: string;
            settled: boolean;
            participantsCount: number;
        };
        LeaderboardResponse: {
            /**
             * @description bytes32 hex (e.g., tournament ID, transaction hash)
             * @example 0xabcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789
             */
            tournamentId: string;
            items: components["schemas"]["LeaderboardEntry"][];
            pagination: {
                /** @description Cursor for the next page. Absent when no more results. */
                next?: string;
            };
        };
        LeaderboardEntry: {
            rank: number;
            /**
             * @description EVM wallet address (checksum or lowercase)
             * @example 0x1234567890abcdef1234567890abcdef12345678
             */
            player: string;
            /**
             * @description uint256 as decimal string (JSON cannot represent BigInt)
             * @example 1000000
             */
            score: string;
            blockNumber: number;
            /**
             * @description bytes32 hex (e.g., tournament ID, transaction hash)
             * @example 0xabcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789
             */
            transactionHash: string;
            timestamp: number;
        };
        ScoreHistoryResponse: {
            /**
             * @description EVM wallet address (checksum or lowercase)
             * @example 0x1234567890abcdef1234567890abcdef12345678
             */
            wallet: string;
            items: components["schemas"]["ScoreEntry"][];
            pagination: {
                /** @description Cursor for the next page. Absent when no more results. */
                next?: string;
            };
        };
        ScoreEntry: {
            /**
             * @description bytes32 hex (e.g., tournament ID, transaction hash)
             * @example 0xabcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789
             */
            tournamentId: string;
            /**
             * @description EVM wallet address (checksum or lowercase)
             * @example 0x1234567890abcdef1234567890abcdef12345678
             */
            player: string;
            /**
             * @description Raw submitted score, pre-cap.
             * @example 1000000
             */
            score: string;
            /**
             * @description uint256 as decimal string (JSON cannot represent BigInt)
             * @example 1000000
             */
            matchCountDelta: string;
            /**
             * @description bytes32 hex (e.g., tournament ID, transaction hash)
             * @example 0xabcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789
             */
            nonce: string;
            blockNumber: number;
            /**
             * @description bytes32 hex (e.g., tournament ID, transaction hash)
             * @example 0xabcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789
             */
            transactionHash: string;
            /** @description Unix seconds at block. */
            timestamp: number;
        };
        ScoreSubmitResponse: {
            /**
             * @description On-chain submitSoloScore broadcast hash. Fire-and-forget — not waited for inclusion.
             * @example 0xabcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789
             */
            txHash: string;
            /**
             * @description bytes32 hex (e.g., tournament ID, transaction hash)
             * @example 0xabcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789
             */
            soloRunId: string;
            /** Format: date-time */
            submittedAt: string;
            /**
             * @description Confirms the trust tier server applied. Echoed in X-SkillOS-Tier header.
             * @enum {string}
             */
            tier: "T0";
        };
        ScoreSubmitRequest: {
            /**
             * @description bytes32 hex (e.g., tournament ID, transaction hash)
             * @example 0xabcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789
             */
            tournamentId: string;
            /** @description Raw player score. T0 tier: server signs as-is, no plausibility validation. */
            score: number;
            /**
             * @description Client-supplied bytes32; if omitted, server generates random.
             * @example 0xabcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789
             */
            soloRunId?: string;
            /**
             * @description Match count increment (capped at MATCH_COUNT_CAP=10 on-chain). 1 by default.
             * @default 1
             */
            matchCountDelta: number;
            /**
             * @description Quality tier per spec. Sprint X2 only validates T0 (signature-only). T1+ rejected with 501.
             * @default T0
             * @enum {string}
             */
            tier: "T0" | "T1" | "T2" | "T3";
        };
        SponsorReceiptsResponse: {
            /**
             * @description EVM wallet address (checksum or lowercase)
             * @example 0x1234567890abcdef1234567890abcdef12345678
             */
            wallet: string;
            items: components["schemas"]["SponsorReceipt"][];
            pagination: {
                /** @description Cursor for the next page. Absent when no more results. */
                next?: string;
            };
        };
        SponsorReceipt: {
            /**
             * @description ERC-5192 SBT tokenId. Soulbound — never transfers out.
             * @example 1000000
             */
            tokenId: string;
            /**
             * @description bytes32 hex (e.g., tournament ID, transaction hash)
             * @example 0xabcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789
             */
            tournamentId: string;
            /**
             * @description Receipt owner. Same as path :wallet.
             * @example 0x1234567890abcdef1234567890abcdef12345678
             */
            sponsor: string;
            /**
             * @description Sponsorship contribution (USDC, 6 decimals).
             * @example 1000000
             */
            amount: string;
            blockNumber: number;
            /**
             * @description bytes32 hex (e.g., tournament ID, transaction hash)
             * @example 0xabcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789
             */
            transactionHash: string;
            timestamp: number;
        };
        AgentScoreSubmitResponse: {
            /**
             * @description On-chain submitSoloScore broadcast hash (fire-and-forget).
             * @example 0xabcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789
             */
            txHash: string;
            /**
             * @description bytes32 hex (e.g., tournament ID, transaction hash)
             * @example 0xabcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789
             */
            soloRunId: string;
            /** Format: date-time */
            submittedAt: string;
            /** @enum {string} */
            tier: "T0";
            /**
             * @description The verified agent wallet address from the SIWA receipt.
             * @example 0x1234567890abcdef1234567890abcdef12345678
             */
            agentAddress: string;
            agentId: number;
        };
        AgentScoreSubmitRequest: {
            /**
             * @description bytes32 hex (e.g., tournament ID, transaction hash)
             * @example 0xabcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789
             */
            tournamentId: string;
            /**
             * @description Game slug. X10: server uses this to resolve the per-game Builder Code for ERC-8021 dataSuffix attribution on the submitSoloScore broadcast. Required for Path A attribution. Must match the game of the targeted tournamentId — the server does NOT verify this match-up; mis-attribution is the caller risk.
             * @enum {string}
             */
            game: "2048" | "wordle" | "sudoku" | "minesweeper" | "clicker" | "match3";
            /** @description Raw agent score. T0 tier only in v0.1 (signature-only, no plausibility — same constraint as POST /v1/scores). */
            score: number;
            /**
             * @description Client-supplied bytes32; if omitted, server generates random.
             * @example 0xabcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789
             */
            soloRunId?: string;
            /**
             * @description Match count increment (capped at MATCH_COUNT_CAP=10 on-chain).
             * @default 1
             */
            matchCountDelta: number;
            /**
             * @description Quality tier. Sprint X4 supports T0 only — T1+ rejected with 501.
             * @default T0
             * @enum {string}
             */
            tier: "T0" | "T1" | "T2" | "T3";
        };
        AgentProfile: {
            agentId: number;
            /**
             * @description EVM wallet address (checksum or lowercase)
             * @example 0x1234567890abcdef1234567890abcdef12345678
             */
            agentAddress: string;
            displayName?: string;
            preferences?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            updatedAt: string;
        };
        AgentProfilePatchRequest: {
            /** @description Off-chain display name (≤64 chars). */
            displayName?: string;
            /** @description Free-form key/value preferences object. */
            preferences?: {
                [key: string]: unknown;
            };
        };
        SoloMatchStartResponse: {
            /**
             * Format: uuid
             * @description Supabase duel_runs.id. The watch UI subscribes to channel `duel_match_{runId}` on the duel_moves table.
             */
            runId: string;
            /**
             * @description Deterministic match seed; feeds the engine SeededRng and is replay-verifiable.
             * @example 0xabcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789
             */
            seed: string;
            /**
             * @description The on-chain agent identity for this match. For X20 this is the STUDIO_PRIVATE_KEY-derived server address; X21 provisions fresh per-agent wallets.
             * @example 0x1234567890abcdef1234567890abcdef12345678
             */
            agentAddress: string;
            /**
             * Format: uri
             * @description Canonical apex watch URL. Built from APEX_WATCH_BASE_URL + runId.
             */
            watchUrl: string;
            /** Format: date-time */
            startedAt: string;
            /**
             * @description Always "pending" for the 202 response. X15.6: x402 settlement and on-chain chargeRetryFee happen asynchronously after this reply lands; subscribers track progress via the x15_payment_attempts Realtime channel keyed by runId.
             * @enum {string}
             */
            status: "pending";
        };
        SoloMatchStartRequest: {
            /**
             * @description Game slug. X20 ships 2048 only; X21+ broadens to other engines as they stabilise their replay-deterministic mode.
             * @enum {string}
             */
            game: "2048";
        };
        MatchReplay: {
            /**
             * @description bytes32 hex (e.g., tournament ID, transaction hash)
             * @example 0xabcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789
             */
            tournamentId: string;
            /**
             * @description Quality tier (score + seed + duration; replay-verifiable).
             * @enum {string}
             */
            tier: "T2";
            entries: components["schemas"]["MatchReplayEntry"][];
            /**
             * @description True while Phase 1 stub is served; flips to false once the indexer captures per-submission seed + duration.
             * @example true
             */
            sampleData: boolean;
        };
        MatchReplayEntry: {
            /**
             * @description Ordinal index within the tournament (zero-based).
             * @example 0
             */
            submissionIndex: number;
            /**
             * @description EVM wallet address (checksum or lowercase)
             * @example 0x1234567890abcdef1234567890abcdef12345678
             */
            player: string;
            /**
             * @description uint256 as decimal string (JSON cannot represent BigInt)
             * @example 1000000
             */
            score: string;
            /**
             * @description bytes32 hex (e.g., tournament ID, transaction hash)
             * @example 0xabcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789
             */
            seed: string;
            /**
             * @description Game duration in milliseconds.
             * @example 47213
             */
            durationMs: number;
            /**
             * @description On-chain block number for the ScoreSubmitted event.
             * @example 12345678
             */
            blockNumber: number;
            /**
             * @description bytes32 hex (e.g., tournament ID, transaction hash)
             * @example 0xabcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789
             */
            transactionHash: string;
            /**
             * @description Unix seconds at block timestamp.
             * @example 1715000000
             */
            timestamp: number;
        };
        X402PaymentRequirements: {
            /** @example 2 */
            x402Version: number;
            /** @example Payment required */
            error?: string;
            resource: components["schemas"]["X402Resource"];
            accepts: {
                /** @example exact */
                scheme: string;
                /** @example eip155:84532 */
                network: string;
                /**
                 * @description USDC amount in atomic units (6 decimals).
                 * @example 10000
                 */
                amount: string;
                /**
                 * @description USDC contract address for the chosen network.
                 * @example 0x036CbD53842c5426634e7929541eC2318f3dCF7e
                 */
                asset: string;
                /**
                 * @description EVM wallet address (checksum or lowercase)
                 * @example 0x1234567890abcdef1234567890abcdef12345678
                 */
                payTo: string;
                /** @example 300 */
                maxTimeoutSeconds: number;
                /** @description Scheme-specific extras (e.g., EIP-712 name + version). */
                extra?: {
                    [key: string]: unknown;
                };
            }[];
        };
        X402Resource: {
            /** @description Fully-qualified URL of the requested resource. */
            url: string;
            /** @example Tournament match event replay (T2 tier data). */
            description: string;
            /** @example application/json */
            mimeType: string;
        };
        CohortSnapshot: {
            /**
             * @description Unix seconds for the snapshot cut-off.
             * @example 1715000000
             */
            snapshotAt: number;
            /**
             * @description Quality tier (aggregated cohort statistics).
             * @enum {string}
             */
            tier: "T3";
            totals: components["schemas"]["CohortTotals"];
            byGame: components["schemas"]["CohortGameStats"][];
            /**
             * @description True while Phase 1 stub is served; flips to false once the v2_submissions materialised view lands.
             * @example true
             */
            sampleData: boolean;
        };
        CohortTotals: {
            /** @example 24 */
            tournaments: number;
            /** @example 1183 */
            participants: number;
            /** @example 5921 */
            submissions: number;
            /** @example 612 */
            agentSubmissions: number;
        };
        CohortGameStats: {
            /**
             * @description Game slug.
             * @example 2048
             */
            game: string;
            /** @example 412 */
            participants: number;
            /** @example 1837 */
            submissions: number;
            /**
             * @description uint256 as decimal string (JSON cannot represent BigInt)
             * @example 1000000
             */
            medianScore: string;
            /**
             * @description uint256 as decimal string (JSON cannot represent BigInt)
             * @example 1000000
             */
            p90Score: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
