// Fetch the live OpenAPI spec from api.skillos.network and run
// openapi-typescript against it. Output committed to src/api.gen.ts as the
// SDK's source of truth for API types.
//
// Override target spec via SKILLOS_OPENAPI_URL env var (for local API dev).
//
// Runs on `prebuild` so the published bundle always reflects the latest API
// contract. CI-friendly: exits non-zero on unreachable spec — we never ship
// stale types.

import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const here = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(here, '../src/api.gen.ts');
const SPEC_URL =
  process.env.SKILLOS_OPENAPI_URL ?? 'https://api.skillos.network/openapi.json';

async function main(): Promise<void> {
  console.log(`[generate-types] fetching ${SPEC_URL}`);
  const ast = await openapiTS(new URL(SPEC_URL));
  const banner =
    '// AUTO-GENERATED by scripts/generate-types.ts — do not edit by hand.\n' +
    '// Source of truth: GET https://api.skillos.network/openapi.json\n' +
    '// Regenerate via: npm run generate-types\n\n';
  writeFileSync(OUT, banner + astToString(ast));
  console.log(`[generate-types] wrote ${OUT}`);
}

main().catch((err: unknown) => {
  console.error('[generate-types] FAIL:', err);
  process.exit(1);
});
