// ───────────────────────────────────────────────────────────────────────────
// X23.1 — Determinism tests for the Glicko-2 wrapper.
//
// Run from package dir:  npx tsx --test test/update.test.ts
// Or from monorepo root: tsx --test packages/glicko-rating/test/update.test.ts
//
// Coverage map (per docs/sprints/x23-glicko-2/SPEC.md §G.1):
//   1. Canonical Glickman 2013 paper worked example, translated to SkillOS
//      anchor 1000 — locks the library version + proves wrapper preserves
//      the paper's math exactly. Translation invariance is a property of
//      Glicko-2 (shifting all ratings by the same constant preserves deltas).
//   2. DEFAULT_RATING constants match SkillOS lock (1000 / 350 / 0.06).
//   3. Empty matches array inflates RD only (per Glicko-2 spec §5.2
//      formula phi* = sqrt(phi² + sigma²)) — useful for cron skipping
//      rating periods for inactive players.
//   4. Equal-rated single-match win produces a predictable rating gain.
//   5. tau override produces different volatility output than the default.
//
// Expected values for tests 1, 3, 4, 5 were generated by direct call into
// glicko2-lite@5.0.0 and verified against the Glickman 2013 paper
// (http://www.glicko.net/glicko/glicko2.pdf) for the canonical case. Exact
// equality is intentional — locks library v5.x behavior; if upstream
// changes its numerical output, the test fails loudly, which is exactly
// the drift signal the SPEC §G.1 calls for.
// ───────────────────────────────────────────────────────────────────────────

import { describe, it } from "node:test";
import assert from "node:assert/strict";
import {
  updateRating,
  DEFAULT_RATING,
  DEFAULT_TAU,
  type MatchOutcome,
} from "../src/index.js";

describe("DEFAULT_RATING constants", () => {
  it("matches SkillOS lock (1000 / 350 / 0.06)", () => {
    assert.equal(DEFAULT_RATING.rating, 1000);
    assert.equal(DEFAULT_RATING.rd, 350);
    assert.equal(DEFAULT_RATING.volatility, 0.06);
  });

  it("exposes DEFAULT_TAU = 0.5 per Glicko-2 paper", () => {
    assert.equal(DEFAULT_TAU, 0.5);
  });
});

describe("updateRating — canonical Glickman 2013 worked example", () => {
  // Glickman 2013 "Example calculation" (paper §example):
  //   player (1500, 200, 0.06) plays 3 opponents:
  //     (1400, 30) — win
  //     (1550, 100) — loss
  //     (1700, 300) — loss
  //   tau = 0.5
  //   expected:  ~1464.06  / ~151.52  / ~0.05999
  //
  // SkillOS uses anchor 1000 (vs paper's 1500). Per Glicko-2 translation
  // invariance, shifting ALL ratings by -500 preserves the rating delta,
  // RD, and volatility. So the wrapper's output at SkillOS anchor should
  // be 1464.06 - 500 = 964.06.
  it("reproduces paper output at SkillOS anchor (input shifted -500)", () => {
    const current = { rating: 1000, rd: 200, volatility: 0.06 };
    const matches: MatchOutcome[] = [
      { opponent: { rating: 900, rd: 30, volatility: 0.06 }, score: 1 },
      { opponent: { rating: 1050, rd: 100, volatility: 0.06 }, score: 0 },
      { opponent: { rating: 1200, rd: 300, volatility: 0.06 }, score: 0 },
    ];

    const next = updateRating(current, matches);

    // Library v5.0.0 emits these exact values; locks upstream behavior.
    assert.equal(next.rating, 964.0506705393013);
    assert.equal(next.rd, 151.51652412385727);
    assert.equal(next.volatility, 0.059995984286488495);
  });
});

describe("updateRating — empty matches array", () => {
  // Per Glicko-2 spec §5.2: if no games are played in a rating period,
  // only RD updates via phi* = sqrt(phi² + sigma²). Rating + volatility
  // stay unchanged. The library implements this correctly; the wrapper
  // must pass through.
  it("inflates RD only; rating and volatility unchanged", () => {
    const next = updateRating(DEFAULT_RATING, []);

    assert.equal(next.rating, 1000);
    assert.equal(next.rd, 350.15516610002004);
    assert.equal(next.volatility, 0.06);
  });
});

describe("updateRating — equal-rated single-match win", () => {
  it("predictable rating gain when defeating an equal opponent", () => {
    const current = { rating: 1000, rd: 350, volatility: 0.06 };
    const matches: MatchOutcome[] = [
      { opponent: { rating: 1000, rd: 350, volatility: 0.06 }, score: 1 },
    ];

    const next = updateRating(current, matches);

    assert.equal(next.rating, 1162.3108939062977);
    assert.equal(next.rd, 290.31896371798047);
    assert.equal(next.volatility, 0.05999967537233814);
  });
});

describe("updateRating — tau parameter override", () => {
  // tau (the system constant) controls how much volatility can change
  // per rating period. Lower tau = more conservative volatility updates.
  // Default 0.5 (Glicko-2 paper); tunable per SPEC §J.1 if leaderboard
  // skew demands it post-mainnet.
  it("custom tau changes volatility output vs default", () => {
    const current = { rating: 1500, rd: 200, volatility: 0.06 };
    const matches: MatchOutcome[] = [
      { opponent: { rating: 1400, rd: 30, volatility: 0.06 }, score: 1 },
    ];

    const withTauDefault = updateRating(current, matches);
    const withTauTight = updateRating(current, matches, 0.3);

    assert.notEqual(
      withTauDefault.volatility,
      withTauTight.volatility,
      "tau override must produce a different volatility than the default",
    );
    // Exact lock on the 0.3-tau output to detect upstream numerical drift:
    assert.equal(withTauTight.volatility, 0.05999951661598805);
  });
});
