// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import { IERC20 } from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import { SafeERC20 } from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import { ReentrancyGuard } from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import { Ownable } from "@openzeppelin/contracts/access/Ownable.sol";
import { ECDSA } from "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";

/// @title ChallengeEscrow
/// @notice Non-custodial on-chain escrow for 1v1 game challenges.
/// @author ceos.run (Simpl3 Inc.)
/// @dev Flow:
///   1. Creator calls createChallenge() — deposits stake.
///   2. Challenger calls acceptChallenge() — deposits equal stake.
///   3. Server determines winner, signs attestation, client calls settle().
///   4. Winner receives totalPool minus 10% platform fee.
///
/// Fee math (Seçenek A):
///   Alice stake 1.00 + Bob stake 1.00 → totalPool = 2.00
///   fee = 2.00 × 10% = 0.20 → payout = 1.80 (winner takes all)
///
/// Walkover: server signs if accepted challenge expires w/o score submission.
/// ReentrancyGuard on all state-changing externals.
/// SafeERC20 on all USDC transfers.
contract ChallengeEscrow is Ownable, ReentrancyGuard {
    using SafeERC20 for IERC20;

    // ─── Errors ────────────────────────────────────────────────────────────────

    error ChallengeAlreadyExists();
    error ChallengeNotOpen();
    error ChallengeNotAccepted();
    error ChallengeHasExpired();
    error ChallengeNotExpired();
    error SelfChallenge();
    error AlreadyAccepted();
    error InvalidWinner();
    error BadSignature();
    error ZeroAddress();
    error ZeroStake();
    error ZeroDuration();

    // ─── Types ─────────────────────────────────────────────────────────────────

    enum Status {
        None,
        Open,
        Accepted,
        Settled,
        Expired,
        Walkover
    }

    struct Challenge {
        address creator;
        address challenger;
        bytes32 gameSlug;
        uint256 stake;
        uint256 createdAt;
        uint256 acceptedAt;
        uint256 expiresAt;
        Status status;
        address winner;
        uint256 payoutAmount;
    }

    // ─── Constants ─────────────────────────────────────────────────────────────

    /// @notice Platform fee in basis points (10% = 1000 bps).
    uint256 public constant FEE_BPS = 1000;
    uint256 private constant BPS_DENOMINATOR = 10_000;

    // ─── State ─────────────────────────────────────────────────────────────────

    /// @notice USDC token on Base (6 decimals).
    IERC20 public immutable USDC;

    /// @notice Server-side EOA that signs settlement attestations.
    address public trustedSigner;

    /// @notice Destination for collected platform fees.
    address public feeVault;

    /// @notice Challenge storage keyed by client-generated bytes32 id.
    mapping(bytes32 => Challenge) public challenges;

    // ─── Events ────────────────────────────────────────────────────────────────

    event ChallengeCreated(
        bytes32 indexed id,
        address indexed creator,
        bytes32 gameSlug,
        uint256 stake,
        uint256 expiresAt
    );
    event ChallengeAccepted(bytes32 indexed id, address indexed challenger);
    event ChallengeSettled(bytes32 indexed id, address indexed winner, uint256 payout);
    event ChallengeExpired(bytes32 indexed id);
    event FeeVaultUpdated(address indexed newVault);
    event TrustedSignerUpdated(address indexed newSigner);

    // ─── Constructor ───────────────────────────────────────────────────────────

    constructor(IERC20 _usdc, address _trustedSigner, address _feeVault) Ownable(msg.sender) {
        if (address(_usdc) == address(0)) revert ZeroAddress();
        if (_trustedSigner == address(0)) revert ZeroAddress();
        if (_feeVault == address(0)) revert ZeroAddress();
        USDC = _usdc;
        trustedSigner = _trustedSigner;
        feeVault = _feeVault;
    }

    // ─── Challenge Lifecycle ───────────────────────────────────────────────────

    /// @notice Create a new challenge, depositing stake into escrow.
    /// @dev    id must be globally unique — server generates a bytes32 from UUID.
    /// @param  id       Unique challenge identifier (bytes32 from server-generated UUID).
    /// @param  gameSlug Game identifier (e.g. keccak256("pilot")).
    /// @param  stake    USDC amount (6 decimals). Challenger must match this exactly.
    /// @param  duration Seconds until open challenge expires (no accept → refund).
    function createChallenge(
        bytes32 id,
        bytes32 gameSlug,
        uint256 stake,
        uint256 duration
    )
        external
        nonReentrant
    {
        if (challenges[id].status != Status.None) revert ChallengeAlreadyExists();
        if (stake == 0) revert ZeroStake();
        if (duration == 0) revert ZeroDuration();

        USDC.safeTransferFrom(msg.sender, address(this), stake);

        challenges[id] = Challenge({
            creator: msg.sender,
            challenger: address(0),
            gameSlug: gameSlug,
            stake: stake,
            createdAt: block.timestamp,
            acceptedAt: 0,
            expiresAt: block.timestamp + duration,
            status: Status.Open,
            winner: address(0),
            payoutAmount: 0
        });

        emit ChallengeCreated(id, msg.sender, gameSlug, stake, block.timestamp + duration);
    }

    /// @notice Accept an open challenge, depositing equal stake.
    /// @param  id  Challenge to accept.
    function acceptChallenge(bytes32 id) external nonReentrant {
        Challenge storage c = challenges[id];
        if (c.status != Status.Open) revert ChallengeNotOpen();
        if (block.timestamp >= c.expiresAt) revert ChallengeHasExpired();
        if (msg.sender == c.creator) revert SelfChallenge();
        if (c.challenger != address(0)) revert AlreadyAccepted();

        USDC.safeTransferFrom(msg.sender, address(this), c.stake);

        c.challenger = msg.sender;
        c.acceptedAt = block.timestamp;
        c.status = Status.Accepted;

        emit ChallengeAccepted(id, msg.sender);
    }

    /// @notice Settle an accepted challenge via server-signed attestation.
    /// @dev    Anyone can call this once a valid signature is obtained from the server.
    ///         Digest: keccak256(abi.encode(id, winner, creatorScore, challengerScore, address(this), block.chainid))
    /// @param  id               Challenge identifier.
    /// @param  winner           Address receiving the payout.
    /// @param  creatorScore     Creator's final game score (informational, bound to sig).
    /// @param  challengerScore  Challenger's final game score (informational, bound to sig).
    /// @param  signature        ECDSA signature from trustedSigner over the digest.
    function settle(
        bytes32 id,
        address winner,
        uint256 creatorScore,
        uint256 challengerScore,
        bytes calldata signature
    )
        external
        nonReentrant
    {
        Challenge storage c = challenges[id];
        if (c.status != Status.Accepted) revert ChallengeNotAccepted();
        if (winner != c.creator && winner != c.challenger) revert InvalidWinner();

        _verifySettleSignature(id, winner, creatorScore, challengerScore, signature);

        uint256 totalPool = c.stake * 2;
        uint256 fee = (totalPool * FEE_BPS) / BPS_DENOMINATOR;
        uint256 payout = totalPool - fee;

        c.status = Status.Settled;
        c.winner = winner;
        c.payoutAmount = payout;

        USDC.safeTransfer(winner, payout);
        if (fee > 0 && feeVault != address(0)) {
            USDC.safeTransfer(feeVault, fee);
        }

        emit ChallengeSettled(id, winner, payout);
    }

    /// @notice Refund creator if nobody accepted before expiry.
    /// @param  id  Challenge identifier (must be Open + expired).
    function expireOpen(bytes32 id) external nonReentrant {
        Challenge storage c = challenges[id];
        if (c.status != Status.Open) revert ChallengeNotOpen();
        if (block.timestamp < c.expiresAt) revert ChallengeNotExpired();

        c.status = Status.Expired;
        USDC.safeTransfer(c.creator, c.stake);

        emit ChallengeExpired(id);
    }

    /// @notice Refund both parties if an accepted challenge expires without settlement.
    /// @param  id  Challenge identifier (must be Accepted + expired).
    function expireAccepted(bytes32 id) external nonReentrant {
        Challenge storage c = challenges[id];
        if (c.status != Status.Accepted) revert ChallengeNotAccepted();
        if (block.timestamp < c.expiresAt) revert ChallengeNotExpired();

        c.status = Status.Expired;
        USDC.safeTransfer(c.creator, c.stake);
        USDC.safeTransfer(c.challenger, c.stake);

        emit ChallengeExpired(id);
    }

    /// @notice Award an accepted-but-expired challenge to one party via server attestation.
    /// @dev    Used when one player submits a score but the other doesn't — server decides.
    ///         Walkover digest: keccak256(abi.encode(id, winner, "walkover", address(this), block.chainid))
    /// @param  id         Challenge identifier.
    /// @param  winner     Awarded party.
    /// @param  signature  ECDSA signature from trustedSigner over the walkover digest.
    function walkover(bytes32 id, address winner, bytes calldata signature) external nonReentrant {
        Challenge storage c = challenges[id];
        if (c.status != Status.Accepted) revert ChallengeNotAccepted();
        if (block.timestamp < c.expiresAt) revert ChallengeNotExpired();
        if (winner != c.creator && winner != c.challenger) revert InvalidWinner();

        _verifyWalkoverSignature(id, winner, signature);

        uint256 totalPool = c.stake * 2;
        uint256 fee = (totalPool * FEE_BPS) / BPS_DENOMINATOR;
        uint256 payout = totalPool - fee;

        c.status = Status.Walkover;
        c.winner = winner;
        c.payoutAmount = payout;

        USDC.safeTransfer(winner, payout);
        if (fee > 0 && feeVault != address(0)) {
            USDC.safeTransfer(feeVault, fee);
        }

        emit ChallengeSettled(id, winner, payout);
    }

    // ─── Admin ─────────────────────────────────────────────────────────────────

    /// @notice Update the fee vault address.
    function setFeeVault(address newVault) external onlyOwner {
        if (newVault == address(0)) revert ZeroAddress();
        feeVault = newVault;
        emit FeeVaultUpdated(newVault);
    }

    /// @notice Update the trusted signer address.
    function setTrustedSigner(address newSigner) external onlyOwner {
        if (newSigner == address(0)) revert ZeroAddress();
        trustedSigner = newSigner;
        emit TrustedSignerUpdated(newSigner);
    }

    /// @notice Emergency withdrawal — only callable by owner, drains entire USDC balance.
    /// @dev    Safety valve. Should never be needed in normal operation.
    function emergencyWithdraw(address to) external onlyOwner {
        if (to == address(0)) revert ZeroAddress();
        uint256 balance = USDC.balanceOf(address(this));
        USDC.safeTransfer(to, balance);
    }

    // ─── View ──────────────────────────────────────────────────────────────────

    /// @notice Returns the challenge struct for a given id.
    function getChallenge(bytes32 id) external view returns (Challenge memory) {
        return challenges[id];
    }

    // ─── Internal ──────────────────────────────────────────────────────────────

    function _verifySettleSignature(
        bytes32 id,
        address winner,
        uint256 creatorScore,
        uint256 challengerScore,
        bytes calldata signature
    )
        internal
        view
    {
        bytes32 digest = keccak256(abi.encode(id, winner, creatorScore, challengerScore, address(this), block.chainid));
        bytes32 ethDigest = keccak256(abi.encodePacked("\x19Ethereum Signed Message:\n32", digest));
        address signer = ECDSA.recover(ethDigest, signature);
        if (signer != trustedSigner) revert BadSignature();
    }

    function _verifyWalkoverSignature(bytes32 id, address winner, bytes calldata signature) internal view {
        bytes32 digest = keccak256(abi.encode(id, winner, "walkover", address(this), block.chainid));
        bytes32 ethDigest = keccak256(abi.encodePacked("\x19Ethereum Signed Message:\n32", digest));
        address signer = ECDSA.recover(ethDigest, signature);
        if (signer != trustedSigner) revert BadSignature();
    }
}
