// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import { IERC20 } from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import { SafeERC20 } from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import { ReentrancyGuard } from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import { Ownable } from "@openzeppelin/contracts/access/Ownable.sol";
import { ECDSA } from "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";

/// @title TournamentPool
/// @notice Sponsored sweepstakes tournaments — free entry, sponsor-funded prizes.
/// @author ceos.run (Simpl3 Inc.)
/// @dev Flow:
///   1. Sponsor calls createTournament() — deposits prize pool in USDC.
///   2. Backend signs EIP-191 attestations; anyone relays submitScore().
///   3. Backend flags implausible scores via flagScore() before settle.
///   4. After endsAt, anyone calls settle(id, sortedRanking) — contract verifies
///      the caller-supplied ordering and distributes per the top-50% curve.
///
/// Prize curve (top 50% = ceil(N/2), applied in bps of prizePool):
///   place 1 — 2500 bps
///   place 2 — 1500 bps
///   place 3 — 1000 bps
///   places 4..min(10, topN) — 500 bps each
///   places 11..topN — 1500 bps / (topN - 10), split equally
///   N < 4 degenerate — place 1 takes 100%
///
/// Unused pool (when the curve doesn't reach 100% for small N, or integer-div
/// dust in the tier-5 split) refunds to the sponsor. This preserves the spec's
/// literal breakdown without inflating top-place shares.
///
/// Effective ranking score (integer math, no division on-chain):
///   effective(p) = bestScore(p) * 85 + matchCount(p) * participationBonus * 15
/// Ties are resolved by caller-supplied order — the contract only verifies
/// monotonic-descending effective scores, not that the order is canonical.
contract TournamentPool is Ownable, ReentrancyGuard {
    using SafeERC20 for IERC20;

    // ─── Errors ────────────────────────────────────────────────────────────────

    error TournamentAlreadyExists();
    error TournamentNotFound();
    error TournamentAlreadySettled();
    error TournamentNotEnded();
    error TournamentAlreadyEnded();
    error TournamentNotStarted();
    error InvalidWindow();
    error ZeroPrize();
    error ZeroAddress();
    error BadSignature();
    error NonceUsed();
    error PlayerNotInTournament();
    error InvalidRankingLength();
    error InvalidRankingOrder();
    error NotParticipant();
    error PlayerExcluded();
    error DuplicateInRanking();

    // ─── Types ─────────────────────────────────────────────────────────────────

    enum CycleType {
        Daily,
        Weekly
    }

    struct Tournament {
        address sponsor;
        bytes32 game;
        CycleType cycleType;
        uint64 startsAt;
        uint64 endsAt;
        uint256 prizePool;
        uint256 participationBonus;
        bool settled;
        address[] participants;
    }

    struct RankEntry {
        address player;
        uint256 effectiveScore;
    }

    // ─── Constants ─────────────────────────────────────────────────────────────

    uint256 private constant BPS_DENOMINATOR = 10_000;

    /// @notice Best-score weight (x85 in effective score integer math).
    uint256 public constant SCORE_WEIGHT = 85;

    /// @notice Participation weight (x15 in effective score integer math).
    uint256 public constant PARTICIPATION_WEIGHT = 15;

    // Prize curve in basis points of prizePool.
    uint256 private constant BPS_PLACE_1 = 2500;
    uint256 private constant BPS_PLACE_2 = 1500;
    uint256 private constant BPS_PLACE_3 = 1000;
    uint256 private constant BPS_PLACES_4_TO_10 = 500;
    uint256 private constant BPS_TIER5_POOL = 1500;
    uint256 private constant TIER5_START_INDEX = 10; // 0-indexed: starts at place 11

    // ─── State ─────────────────────────────────────────────────────────────────

    /// @notice USDC token (6 decimals) used for prize pools.
    IERC20 public immutable USDC;

    /// @notice Server-side EOA that signs submit attestations.
    address public trustedSigner;

    /// @notice Tournament storage keyed by client-generated bytes32 id.
    mapping(bytes32 => Tournament) internal _tournaments;

    /// @notice Per-tournament, per-player best score (raw game score, not weighted).
    mapping(bytes32 => mapping(address => uint256)) public bestScore;

    /// @notice Per-tournament, per-player cumulative match count.
    mapping(bytes32 => mapping(address => uint256)) public matchCount;

    /// @notice Per-tournament, per-player excluded flag (set by flagScore before settle).
    mapping(bytes32 => mapping(address => bool)) public excluded;

    /// @notice Per-tournament, per-player participation flag (true after first submitScore).
    mapping(bytes32 => mapping(address => bool)) public isParticipant;

    /// @notice Global nonce map for submitScore attestations — prevents replay across all tournaments.
    mapping(bytes32 => bool) public usedNonces;

    /// @notice Internal seen-set for settle ranking validation. Not cleared on settle
    ///         success because a settled tournament can never be settled again.
    mapping(bytes32 => mapping(address => bool)) private _seenInRanking;

    // ─── Events ────────────────────────────────────────────────────────────────

    event TournamentCreated(
        bytes32 indexed id,
        address indexed sponsor,
        bytes32 indexed game,
        CycleType cycleType,
        uint64 startsAt,
        uint64 endsAt,
        uint256 prizePool,
        uint256 participationBonus
    );
    event ScoreSubmitted(
        bytes32 indexed id,
        address indexed player,
        uint256 score,
        uint256 matchCountDelta,
        bytes32 nonce
    );
    event ScoreFlagged(bytes32 indexed id, address indexed player);
    event TournamentSettled(bytes32 indexed id, uint256 totalDistributed, uint256 refunded);
    event PrizePaid(bytes32 indexed id, address indexed player, uint256 place, uint256 amount);
    event TrustedSignerUpdated(address indexed newSigner);

    // ─── Constructor ───────────────────────────────────────────────────────────

    constructor(IERC20 _usdc, address _trustedSigner) Ownable(msg.sender) {
        if (address(_usdc) == address(0)) revert ZeroAddress();
        if (_trustedSigner == address(0)) revert ZeroAddress();
        USDC = _usdc;
        trustedSigner = _trustedSigner;
    }

    // ─── Tournament Lifecycle ──────────────────────────────────────────────────

    /// @notice Create a sponsored tournament and deposit the prize pool.
    /// @dev    Caller becomes the sponsor. Prize pool must be pre-approved.
    /// @param  id                   Client-generated bytes32 tournament id.
    /// @param  game                 Game slug (keccak256(utf8(name))).
    /// @param  cycleType            Daily or Weekly (informational — endsAt controls settlement).
    /// @param  startsAt             Unix timestamp when submission opens.
    /// @param  endsAt               Unix timestamp when submission closes + settle unlocks.
    /// @param  prizePool            USDC amount the sponsor deposits (6 decimals).
    /// @param  participationBonus   Per-tournament constant added per match to effective score.
    function createTournament(
        bytes32 id,
        bytes32 game,
        CycleType cycleType,
        uint64 startsAt,
        uint64 endsAt,
        uint256 prizePool,
        uint256 participationBonus
    )
        external
        nonReentrant
    {
        if (_tournaments[id].sponsor != address(0)) revert TournamentAlreadyExists();
        if (endsAt <= startsAt) revert InvalidWindow();
        if (prizePool == 0) revert ZeroPrize();

        USDC.safeTransferFrom(msg.sender, address(this), prizePool);

        Tournament storage t = _tournaments[id];
        t.sponsor = msg.sender;
        t.game = game;
        t.cycleType = cycleType;
        t.startsAt = startsAt;
        t.endsAt = endsAt;
        t.prizePool = prizePool;
        t.participationBonus = participationBonus;

        emit TournamentCreated(id, msg.sender, game, cycleType, startsAt, endsAt, prizePool, participationBonus);
    }

    /// @notice Submit a player's score via backend-signed attestation.
    /// @dev    Digest: keccak256(abi.encode(id, player, score, matchCountDelta, nonce, address(this), block.chainid))
    /// @param  id               Tournament identifier.
    /// @param  player           Player whose score is being recorded.
    /// @param  score            Raw game score — stored as bestScore if it exceeds the prior best.
    /// @param  matchCountDelta  Added to the player's matchCount (usually 1 per submission).
    /// @param  nonce            Unique per-submission nonce from backend for replay protection.
    /// @param  signature        ECDSA signature from trustedSigner over the digest.
    function submitScore(
        bytes32 id,
        address player,
        uint256 score,
        uint256 matchCountDelta,
        bytes32 nonce,
        bytes calldata signature
    )
        external
    {
        Tournament storage t = _tournaments[id];
        if (t.sponsor == address(0)) revert TournamentNotFound();
        if (t.settled) revert TournamentAlreadySettled();
        if (block.timestamp < t.startsAt) revert TournamentNotStarted();
        if (block.timestamp >= t.endsAt) revert TournamentAlreadyEnded();
        if (usedNonces[nonce]) revert NonceUsed();
        if (player == address(0)) revert ZeroAddress();

        _verifySubmitSignature(id, player, score, matchCountDelta, nonce, signature);

        usedNonces[nonce] = true;

        if (!isParticipant[id][player]) {
            isParticipant[id][player] = true;
            t.participants.push(player);
        }

        if (score > bestScore[id][player]) {
            bestScore[id][player] = score;
        }
        matchCount[id][player] += matchCountDelta;

        emit ScoreSubmitted(id, player, score, matchCountDelta, nonce);
    }

    /// @notice Mark a player as excluded (anti-cheat veto). Must be called before settle.
    /// @dev    Owner-only. Excluded players are skipped in ranking + prize distribution.
    function flagScore(bytes32 id, address player) external onlyOwner {
        Tournament storage t = _tournaments[id];
        if (t.sponsor == address(0)) revert TournamentNotFound();
        if (t.settled) revert TournamentAlreadySettled();
        if (!isParticipant[id][player]) revert PlayerNotInTournament();

        excluded[id][player] = true;
        emit ScoreFlagged(id, player);
    }

    /// @notice Settle a tournament — distribute prizes per the top-50% curve.
    /// @dev    Anyone may call after endsAt. Caller passes the pre-sorted ranking
    ///         (non-excluded participants, descending effective score). Contract
    ///         verifies completeness + order + no-duplicate, then pays out.
    ///         Unused pool (small-N leftover, tier-5 dust) refunds to sponsor.
    /// @param  id              Tournament identifier.
    /// @param  sortedRanking   Participants ordered by descending effective score.
    function settle(bytes32 id, address[] calldata sortedRanking) external nonReentrant {
        Tournament storage t = _tournaments[id];
        if (t.sponsor == address(0)) revert TournamentNotFound();
        if (t.settled) revert TournamentAlreadySettled();
        if (block.timestamp < t.endsAt) revert TournamentNotEnded();

        uint256 expectedCount = _countNonExcluded(id, t);
        if (sortedRanking.length != expectedCount) revert InvalidRankingLength();

        // Early mark as settled — reentrancy-safe and also locks in the state before
        // any external USDC transfers.
        t.settled = true;

        _verifyRanking(id, t, sortedRanking);

        uint256 totalDistributed = _distributePrizes(id, t, sortedRanking);

        uint256 refunded = 0;
        if (totalDistributed < t.prizePool) {
            refunded = t.prizePool - totalDistributed;
            USDC.safeTransfer(t.sponsor, refunded);
        }

        emit TournamentSettled(id, totalDistributed, refunded);
    }

    // ─── Admin ─────────────────────────────────────────────────────────────────

    function setTrustedSigner(address newSigner) external onlyOwner {
        if (newSigner == address(0)) revert ZeroAddress();
        trustedSigner = newSigner;
        emit TrustedSignerUpdated(newSigner);
    }

    /// @notice Emergency withdrawal of any stuck USDC. Owner-only safety valve.
    function emergencyWithdraw(address to) external onlyOwner {
        if (to == address(0)) revert ZeroAddress();
        uint256 balance = USDC.balanceOf(address(this));
        USDC.safeTransfer(to, balance);
    }

    // ─── Views ─────────────────────────────────────────────────────────────────

    function getTournament(bytes32 id) external view returns (Tournament memory) {
        return _tournaments[id];
    }

    function getParticipants(bytes32 id) external view returns (address[] memory) {
        return _tournaments[id].participants;
    }

    function participantCount(bytes32 id) external view returns (uint256) {
        return _tournaments[id].participants.length;
    }

    /// @notice Effective ranking score for a single player.
    /// @dev    Returns 0 for excluded players. Uses integer math only.
    function effectiveScoreOf(bytes32 id, address player) public view returns (uint256) {
        if (excluded[id][player]) return 0;
        return _computeEffectiveScore(
            bestScore[id][player],
            matchCount[id][player],
            _tournaments[id].participationBonus
        );
    }

    /// @notice Returns non-excluded participants sorted by descending effective score.
    /// @dev    O(n^2) insertion sort in memory. View-only; intended for off-chain readers.
    function getRanking(bytes32 id) external view returns (RankEntry[] memory) {
        Tournament storage t = _tournaments[id];
        uint256 n = t.participants.length;

        uint256 count;
        for (uint256 i; i < n; ++i) {
            if (!excluded[id][t.participants[i]]) ++count;
        }

        RankEntry[] memory entries = new RankEntry[](count);
        uint256 idx;
        for (uint256 i; i < n; ++i) {
            address p = t.participants[i];
            if (excluded[id][p]) continue;
            entries[idx++] = RankEntry({
                player: p,
                effectiveScore: _computeEffectiveScore(bestScore[id][p], matchCount[id][p], t.participationBonus)
            });
        }

        // Insertion sort descending.
        for (uint256 i = 1; i < count; ++i) {
            RankEntry memory cur = entries[i];
            uint256 j = i;
            while (j > 0 && entries[j - 1].effectiveScore < cur.effectiveScore) {
                entries[j] = entries[j - 1];
                unchecked { --j; }
            }
            entries[j] = cur;
        }

        return entries;
    }

    // ─── Internal ──────────────────────────────────────────────────────────────

    function _computeEffectiveScore(uint256 best, uint256 mc, uint256 bonus) internal pure returns (uint256) {
        return best * SCORE_WEIGHT + mc * bonus * PARTICIPATION_WEIGHT;
    }

    function _verifySubmitSignature(
        bytes32 id,
        address player,
        uint256 score,
        uint256 matchCountDelta,
        bytes32 nonce,
        bytes calldata signature
    )
        internal
        view
    {
        bytes32 digest =
            keccak256(abi.encode(id, player, score, matchCountDelta, nonce, address(this), block.chainid));
        bytes32 ethDigest = keccak256(abi.encodePacked("\x19Ethereum Signed Message:\n32", digest));
        address signer = ECDSA.recover(ethDigest, signature);
        if (signer != trustedSigner) revert BadSignature();
    }

    function _countNonExcluded(bytes32 id, Tournament storage t) internal view returns (uint256 c) {
        uint256 n = t.participants.length;
        for (uint256 i; i < n; ++i) {
            if (!excluded[id][t.participants[i]]) {
                unchecked { ++c; }
            }
        }
    }

    function _verifyRanking(bytes32 id, Tournament storage t, address[] calldata ranking) internal {
        uint256 len = ranking.length;
        uint256 prevScore = type(uint256).max;
        uint256 bonus = t.participationBonus;

        for (uint256 i; i < len; ++i) {
            address p = ranking[i];
            if (!isParticipant[id][p]) revert NotParticipant();
            if (excluded[id][p]) revert PlayerExcluded();
            if (_seenInRanking[id][p]) revert DuplicateInRanking();
            _seenInRanking[id][p] = true;

            uint256 sc = _computeEffectiveScore(bestScore[id][p], matchCount[id][p], bonus);
            if (sc > prevScore) revert InvalidRankingOrder();
            prevScore = sc;
        }
    }

    function _distributePrizes(bytes32 id, Tournament storage t, address[] calldata ranking)
        internal
        returns (uint256 totalDistributed)
    {
        uint256 n = ranking.length;
        if (n == 0) return 0;

        uint256 pool = t.prizePool;

        // Degenerate: fewer than 4 participants → place 1 takes all.
        if (n < 4) {
            USDC.safeTransfer(ranking[0], pool);
            emit PrizePaid(id, ranking[0], 1, pool);
            return pool;
        }

        uint256 topN = (n + 1) / 2; // ceil(N / 2)

        // Top-3 fixed bps.
        _pay(id, ranking, 0, (pool * BPS_PLACE_1) / BPS_DENOMINATOR);
        _pay(id, ranking, 1, (pool * BPS_PLACE_2) / BPS_DENOMINATOR);
        _pay(id, ranking, 2, (pool * BPS_PLACE_3) / BPS_DENOMINATOR);
        totalDistributed = (pool * BPS_PLACE_1) / BPS_DENOMINATOR
            + (pool * BPS_PLACE_2) / BPS_DENOMINATOR
            + (pool * BPS_PLACE_3) / BPS_DENOMINATOR;

        // Places 4..min(topN, 10) get 500 bps each.
        uint256 tier4End = topN < TIER5_START_INDEX ? topN : TIER5_START_INDEX;
        uint256 perPlace45 = (pool * BPS_PLACES_4_TO_10) / BPS_DENOMINATOR;
        for (uint256 i = 3; i < tier4End; ++i) {
            _pay(id, ranking, i, perPlace45);
            totalDistributed += perPlace45;
        }

        // Places 11..topN split 1500 bps equally. Integer-div dust refunds to sponsor.
        if (topN > TIER5_START_INDEX) {
            uint256 tier5Count = topN - TIER5_START_INDEX;
            uint256 tier5Pool = (pool * BPS_TIER5_POOL) / BPS_DENOMINATOR;
            uint256 perPlaceT5 = tier5Pool / tier5Count;
            if (perPlaceT5 > 0) {
                for (uint256 i = TIER5_START_INDEX; i < topN; ++i) {
                    _pay(id, ranking, i, perPlaceT5);
                    totalDistributed += perPlaceT5;
                }
            }
        }
    }

    function _pay(bytes32 id, address[] calldata ranking, uint256 idx, uint256 amount) internal {
        if (amount == 0) return;
        address winner = ranking[idx];
        USDC.safeTransfer(winner, amount);
        emit PrizePaid(id, winner, idx + 1, amount);
    }
}
